{% set name = "qdrant-client" %}
{% set version = "1.19.0" %}
{% set skip_tests = [
  "--ignore=tests/congruence_tests",
  "--ignore=tests/test_qdrant_client.py",
  "--ignore=tests/test_migrate.py",
  "--ignore=tests/test_async_qdrant_client.py",
  "--deselect=tests/embed_tests/test_local_inference.py::test_bm25_core"
] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name.split('-')[0] }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d388bce332f2a28b253a229c4f6b58f2da0ff919267826ba51334f3809f0d2ca

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
    - setuptools
  run:
    - python
    - httpx >=0.20.0
    - numpy >=1.21,<2.3.0  # [py==310]
    - numpy >=1.21  # [py==311]
    - numpy >=1.26  # [py==312]
    - numpy >=2.1.0  # [py==313]
    - numpy >=2.3.0  # [py>=314]
    - pydantic >=1.10.8,!=2.0.*,!=2.1.*,!=2.2.0
    - grpcio >=1.41.0
    - protobuf >=3.20.0
    - urllib3 >=1.26.14,<3
    - portalocker >=2.7.0,<4.0
  run_constrained:
    - fastembed >=0.8,<0.9
    - fastembed-gpu >=0.8,<0.9

test:
  source_files:
    - tests
    - pyproject.toml
  imports:
    - qdrant_client
  commands:
    - pip check
    - pytest -v {{ skip_tests | join(" ")}}  # [not win]
    - pytest -v {{ skip_tests | join(" ")}} "--ignore=tests/test_local_persistence.py"  # [win]
  requires:
    - pip
    - python
    - pytest >=7.1,<8
    - pytest-asyncio
    - pytest-docker-tools

about:
  home: https://github.com/qdrant/qdrant-client
  summary: Python client for Qdrant vector search engine
  description: |
    Client library and SDK for the Qdrant vector search engine.
    Library contains type definitions for all Qdrant API and allows to make both Sync and Async requests.
    Client allows calls for all Qdrant API methods directly. It also provides some additional
    helper methods for frequently required operations, e.g. initial collection uploading.
  dev_url: https://github.com/qdrant/qdrant-client
  doc_url: https://github.com/qdrant/qdrant-client/blob/master/README.md
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
